version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lumen-app
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    networks:
      - lumen

  web:
    image: nginx:alpine
    container_name: lumen-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lumen

networks:
  lumen:
    driver: bridge
